### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by lechten** [Max-Hailperin/Operating-Systems-and-Middleware--Supporting-Controlled-Interaction#125]
Would you agree to create a new release of the book? Based on version-numbering.html I'm not sure whether that should be 1.2.2 or 1.3.
Should I create a pull request for that? Next to a new PDF file, changes would be necessary in os-book.tex, README.md, and index.html, wouldn't they?

By the way, next week I'll start teaching a course based on your book. I'll publish my presentations over there (draft versions so far, to stabilize throughout the term): https://gitlab.com/oer/OS

Many thanks for releasing this great book under free license terms!

**Comment by Max-Hailperin** [comment]
I agree that a new release is warranted. I would suggest numbering it 1.3 rather than 1.2.2, but it could really go either way.

I would appreciate your preparing the pull request for this. Assuming that by index.html you mean web-site/index.html, then yes, those three files would need to be included in the pull request. (I'm sure there is a better way to automatically derive them all from a common source of the version number, but I never bothered figuring that out.)

In addition to those three, however, I would greatly appreciate your also including the PDF file, which would be web-site/osm-rev1.3.pdf if you advance to release 1.3. I have retired so thoroughly that I literally do not have LaTeX and friends installed on my computer -- and it is a big enough package that I'd rather not install it.

That way, if you do all of that, then I only need to recover the password to the Gustavus web site and push the contents of the web-site directory there.

I'm delighted that you are continuing to find the book useful for your course and are contributing to keep it useful.
