### ISSUE TITLE
Add frame numbers to Figure 6.13

### ISSUE THREAD

**Issue by lechten** [Max-Hailperin/Operating-Systems-and-Middleware--Supporting-Controlled-Interaction#127]
I created a variant of the two-level page table of Figure 6.13, which includes (random) frame numbers: https://gitlab.com/oer/figures/blob/master/OS/hail_f0613_with_frames.pdf

What do you think about using that figure in the book?  Frame numbers are the major pieces of information offered by page tables, and some of my students were confused by their omission.

I edited your PDF figure with LibreOffice.  My source file: https://gitlab.com/oer/figures/blob/master/OS/hail_f0613_with_frames.odg 

Did you already think about the effects of CC BY on attribution information?  The simplest case would be if you released Figure 6.13 under CC0.  Then I could do the same with my version, and no licensing information would be required in the book.  Currently, I suppose that the figure is distributed under CC BY-SA 3.0 (as the book).  Thus, I cannot release my version into the Public Domain (CC0); instead, I now also use CC BY-SA 3.0, which requires that I'm attributed (meta-data is maintained in this file, from which licensing information is generated in my presentations: https://gitlab.com/oer/figures/blob/master/OS/hail_f0613_with_frames.meta).  I'm not sure how to go about that in the context of your book.

**Comment by Max-Hailperin** [comment]
Thank you for doing this. I retired two years ago and so no longer have any involvement with this book or indeed with teaching computer science at all. I haven't taught anyone older than the age of 6 anything in two and a half years now, and as you can imagine, I haven't been teaching the little kids about virtual memory. That makes it hard for me to be confident I am realistically thinking about the educational issues your suggestion raises.My initial reaction is that you are correct that providing frame numbers as well as page numbers improves the clarity, but that the point would be clearer with the page numbers and frame numbers reversed—the page number inside each box and the frame number in the label below the box. That's because the frame is the physical container whereas the page is what it contains. The frame numbers are the same information as is diagrammed by the arrows leading from the page tables—those arrows show *where* each page is located, which is in my mind also consistent with putting the frame number on the outside, which is where I would expect to see a location as opposed to a content. Perhaps it would help to also put the frame number at the tail of each arrow inside the page table, so that with your choices, the left-hand page table

**Comment by Max-Hailperin** [comment]
Another thought: Should frames 99 and 100 be reversed into numerical order, with the arrows from the page table then crossing?

**Comment by lechten** [comment]
Many thanks for your detailed response.  I really appreciate your feedback, in particular in view of your retirement!  Also, many thanks for the licensing clarification.

I understand your reasoning of frames being containers for pages and of arrows showing page locations.  Based on your comments and the general layout of page tables shown in Fig. 6.11, I created another figure without the third layer, where each entry of the page table contains valid information and frame number: https://gitlab.com/oer/figures/blob/master/OS/hail_f0613_with_embedded_frame_nos.pdf

The updated caption could read as follows:

```
  The IA-32 two-level page table has a page directory that can
  point to 1024 chunks of the page table, each of which can point to 1024 page
  frames.  As in Fig. 6.11, entries of the page table record
  valid information and page frame addresses.  For example, the
  leftmost entry of the leftmost chunk of the page table points to the
  page frame holding page~0, which is page frame 0; besides, page
  frame 42 holds page 1023, while page frames 100 and 99 hold pages
  1047552 and 1047553, respectively.
  Each entry can also be
  marked invalid, indicated by an X in this diagram. For example, the
  second entry in the first chunk of the page table is invalid, showing that no
  page frame holds page~1.  The same principle applies at the page
  directory level; in this example, no page frames hold pages 1024--2047,
  so the second page directory entry is marked invalid.
```

What do you think about this?

**Comment by lechten** [comment]
Thanks for the suggestion. I'll change that and create a pull request, maybe tomorrow.
