### ISSUE TITLE
Exploration Project 6.2: Unreasonably long?

### ISSUE THREAD

**Issue by evavreck** [Max-Hailperin/Operating-Systems-and-Middleware--Supporting-Controlled-Interaction#83]
I'm not sure whether this was intentional, but Exploration Project 6.2 says with regards to memory size devoted to various processes to "Use the ps axl command and note the sizes," then to "calculate a ratio of the two sizes for each process." I've checked, and after a restart with no programs running, the command returned a list of 197 processes. Can you perhaps give some method for saving and calculating the values en masse as opposed to writing down and calculating all of them manually?

**Comment by Max-Hailperin** [comment]
The ps command arguments I showed are also incredibly old-fashioned. On both Mac OS X and Linux, the following command will produce a text file named ratios containing a sorted list of the ratios (for those processes with non-zero size):
    ps -A -o rss= -o vsz= | awk '$2!=0 {printf "%f\n",$1/$2}' | sort >ratios

I still have to figure out how to explain this in some way that is reasonably brief yet provides understanding rather than just demanding blind copy-and-paste.
